### ISSUE TITLE
Make a Binder badge

### ISSUE THREAD

**Issue by dotsdl** [MDAnalysis/MDAnalysisCookbook#2]
Once this repo has a nice collection of notebooks, we can submit it to [binder](http://mybinder.org/) to make them immediately executable. We should then feature a badge or link on http://mdanalysis.org so that new users can immediately try them out.

Thanks to @hainm for pointing out this service.

**Comment by hainm** [comment]
In case you need real world example for `environment.yml` file (used for conda install in my case)

https://github.com/hainm/notebook-pytraj/blob/master/environment.yml

**Comment by orbeckst** [comment]
Notebook things: see https://github.com/MDAnalysis/binder-notebook/issues/2

**Comment by kain88-de** [comment]
Oh cool I didn’t notice I closed a two year old issue.
